echo "CREATE DATABASE $1

CREATE CLASS VDocument EXTENDS V

CREATE PROPERTY VDocument.KEY   STRING  (MANDATORY TRUE)
CREATE PROPERTY VDocument.GJAHR INTEGER (MANDATORY TRUE)
CREATE PROPERTY VDocument.BELNR STRING  (MANDATORY TRUE)
CREATE PROPERTY VDocument.BLART STRING  (MANDATORY TRUE)
CREATE PROPERTY VDocument.BLDAT DATE    (MANDATORY TRUE)
CREATE PROPERTY VDocument.BUDAT DATE    (MANDATORY TRUE)

CREATE INDEX VDocument.KEY UNIQUE

CREATE CLASS EClearing EXTENDS E

CREATE PROPERTY EClearing.KEY   STRING  (MANDATORY TRUE)
CREATE PROPERTY EClearing.HKONT STRING  (MANDATORY TRUE)
CREATE PROPERTY EClearing.BUZEI STRING  (MANDATORY TRUE)
CREATE PROPERTY EClearing.SHKZG STRING  (MANDATORY TRUE)
CREATE PROPERTY EClearing.DMBTR DECIMAL (MANDATORY TRUE)

CREATE INDEX EClearing.KEY UNIQUE
"